## **Tugas 7 Modeling Data**


Lakukan analisa terhadap data dengan menggunakan 

- metode naive bayes (
  1. lakukan transformasi data ke numerik karena menggunakan gaussian naive bayes
  2. normalisasi minmax scaler)

- metode pohon keputusan (Desision tree)
- metode KNN

confusion matrix?



In [58]:
import pandas as pd
#membaca data kanker 
data_cs= pd.read_csv('/content/drive/MyDrive/datamining/tugas/credit_score.csv')
#menampilkan 5 data teratas
del data_cs['Unnamed: 0']
data_cs.head()


kode_kontrak  pendapatan_setahun_juta kpr_aktif  durasi_pinjaman_bulan  \
0   AGR-000001                      295        YA                     48   
1   AGR-000011                      271        YA                     36   
2   AGR-000030                      159     TIDAK                     12   
3   AGR-000043                      210        YA                     12   
4   AGR-000049                      165     TIDAK                     36   

   jumlah_tanggungan rata_rata_overdue  risk_rating  
0                  5      61 - 90 days            4  
1                  5      61 - 90 days            4  
2                  0       0 - 30 days            1  
3                  3      46 - 60 days            3  
4                  0      31 - 45 days            2

In [59]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
transformed = ohe.fit_transform(data_cs[['rata_rata_overdue']])
print(transformed.toarray())
print(ohe.categories_)


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[array(['0 - 30 days', '31 - 45 days', '46 - 60 days', '61 - 90 days',
       '> 90 days'], dtype=object)]


In [60]:
data_cs[ohe.categories_[0]] = transformed.toarray()
print(data_cs.head())


  kode_kontrak  pendapatan_setahun_juta kpr_aktif  durasi_pinjaman_bulan  \
0   AGR-000001                      295        YA                     48   
1   AGR-000011                      271        YA                     36   
2   AGR-000030                      159     TIDAK                     12   
3   AGR-000043                      210        YA                     12   
4   AGR-000049                      165     TIDAK                     36   

   jumlah_tanggungan rata_rata_overdue  risk_rating  0 - 30 days  \
0                  5      61 - 90 days            4          0.0   
1                  5      61 - 90 days            4          0.0   
2                  0       0 - 30 days            1          1.0   
3                  3      46 - 60 days            3          0.0   
4                  0      31 - 45 days            2          0.0   

   31 - 45 days  46 - 60 days  61 - 90 days  > 90 days  
0           0.0           0.0           1.0        0.0  
1           0.0     

In [61]:
transformed = ohe.fit_transform(data_cs[['kpr_aktif']])
print(transformed.toarray())

[[0. 1.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [62]:
del data_cs['rata_rata_overdue']
del data_cs['kpr_aktif']

In [65]:
import pandas as pd
import numpy as np
data_cs[ohe.categories_[0]] = transformed.toarray()

print(data_cs.head())

  kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0   AGR-000001                      295                     48   
1   AGR-000011                      271                     36   
2   AGR-000030                      159                     12   
3   AGR-000043                      210                     12   
4   AGR-000049                      165                     36   

   jumlah_tanggungan  risk_rating  0 - 30 days  31 - 45 days  46 - 60 days  \
0                  5            4          0.0           0.0           0.0   
1                  5            4          0.0           0.0           0.0   
2                  0            1          1.0           0.0           0.0   
3                  3            3          0.0           0.0           1.0   
4                  0            2          0.0           1.0           0.0   

   61 - 90 days  > 90 days  TIDAK   YA  
0           1.0        0.0    0.0  1.0  
1           1.0        0.0    0.0  1.0  
2          

In [ ]:
new_order = ['kode_kontrak',  'pendapatan_setahun_juta',	'durasi_pinjaman_bulan',	'jumlah_tanggungan', '0 - 30 days',
             '31 - 45 days',  '46 - 60 days', 'TIDAK',   'YA', '61 - 90 days',  '> 90 days',   'risk_rating']
print(data_cs[data_cs.columns[new_order]]) 

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
cs_new = pd.DataFrame(data_cs, columns=['pendapatan_setahun_juta',	'durasi_pinjaman_bulan',	'jumlah_tanggungan'])
print(scaler.fit(cs_new))

MinMaxScaler()

In [ ]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
test_size = 0.33
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=test_size, random_state=seed)
# Fit the model on training set
model = LogisticRegression()
model.fit(X_train, Y_train)
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
 
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)
print(result)